### ISSUE TITLE
Impact of Giving page - feature image

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#10]
Can we move the blue box/ text on the feature image over to the right? This box cuts off the student's head.
![Screen Shot 2020-03-06 at 9 59 06 AM](https://user-images.githubusercontent.com/60756584/76109368-268ea280-5f91-11ea-8244-ff43f252b6e6.png)

**Comment by Herm71** [comment]
Done.
![Screenshot from 2020-03-06 15-41-43](https://user-images.githubusercontent.com/1000543/76130833-0c6cb880-5fc1-11ea-83ee-1e78d4099de9.png)
