### ISSUE TITLE
Impact of Giving page - photo tiles

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#11]
Can we make the photo tiles below the feature image consistent in size? Can they be the same square size we have on other pages? See the "Ares to Support" page for reference.
![Screen Shot 2020-03-06 at 10 01 20 AM](https://user-images.githubusercontent.com/60756584/76109519-740b0f80-5f91-11ea-9180-38bfefaf310e.png)

**Comment by Herm71** [comment]
We can. This is the same issue as with the thumbnails on the blog page. Once we get "square" images, they'll become uniform.

**Comment by knice** [comment]
I believe this is resolved elsewhere on the site. Closing this since we changed the layout on IoG page.
