### ISSUE TITLE
Contact: Make UC Obs. and Seymour contacts visible in new location

### ISSUE THREAD

**Issue by jhillard-ucsc** [ucsc/site-giving#116]
It makes more sense to put Natasha and Lauren in the part of the contacts page with the divisional gift officers. I moved their entries, but they don't appear now. Please fix.

**Comment by knice** [comment]
The loops for the contact data are hard-coded for the keys in the data file. The template needs to run through the loop based on the generic structure of the data file, not the specific names of the keys.
