### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#13]
- We need more air between the feature image and the phone number/ website

- We also need more air between the phone number/ website and the contact tiles below that.
![Screen Shot 2020-03-06 at 10 05 57 AM](https://user-images.githubusercontent.com/60756584/76109808-19be7e80-5f92-11ea-8208-38e835c6596b.png)

**Comment by Herm71** [comment]
Added 30px.
![Screenshot from 2020-03-06 15-52-17](https://user-images.githubusercontent.com/1000543/76131244-8d787f80-5fc2-11ea-84cc-c20a4eaebe22.png)
