### ISSUE TITLE
Embedded Report mini-pages

### ISSUE THREAD

**Issue by Herm71** [ucsc/site-giving#25]
How to deal them?

**Comment by Herm71** [comment]
Created an Annual Reports page with index. Still not sure about the html ones.

**Comment by knice** [comment]
https://giving.ucsc.edu/reports/2013-14/index.php

**Comment by knice** [comment]
Pull folder down from current site and add to new site repository. We'll fix links, clean content, and make static versions of this stuff after launch.

**Comment by Herm71** [comment]
All Annual Reports now live at `/reports/` with an index. Dynamic php reports converted to static html; pdfs incorporated, too.

**Comment by Herm71** [comment]
Reopening issue and removing from Launch Milestone.

**Comment by Herm71** [comment]
Based on discussions with @knice and @jhillard-ucsc we've decided to leave the reports on the site as an archive, then put a `robots.txt` file in this `dir` so it doesn't get crawled.
