### ISSUE TITLE
Areas to Support tiles

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#26]
I'm not sure if it can be achieved, but right now the buttons move along with the copy in each tile, but visually it might be cleaner if we have the buttons static, in the same place on each tile. Is that possible?
<img width="1044" alt="Screen Shot 2020-04-27 at 9 00 25 AM" src="https://user-images.githubusercontent.com/60756584/80394144-4db57200-8866-11ea-8d1a-7167749a620c.png">

**Comment by Herm71** [comment]
I can check!

**Comment by knice** [comment]
Resolved. Buttons on the bottom of the CTA boxes now. 

![screen-2021-01-11-135331](https://user-images.githubusercontent.com/36719/104242948-b6547700-5414-11eb-8cd1-dca1684b7878.jpg)
