### ISSUE TITLE
Areas to Support  - Yellow lines

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#28]
On my orig design, I have yellow lines diving the page into sections. Did we decide to get rid of those for some reason? If not, I do think it makes sense to have them for consistency across each page. 
<img width="288" alt="Screen Shot 2020-04-27 at 9 24 57 AM" src="https://user-images.githubusercontent.com/60756584/80396202-2ad88d00-8869-11ea-8ca5-8130f55a3ae5.png">

**Comment by Herm71** [comment]
I agree.
