### ISSUE TITLE
New graphic for Giving Tuesday

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#35]
Hi @Herm71 ,

Here is the new image for the Giving Tuesday tile image on the homepage.
<img width="482" alt="Screen Shot 2020-05-06 at 10 13 35 AM" src="https://user-images.githubusercontent.com/60756584/81207431-61f22100-8f82-11ea-8d5d-fc727912066a.png">
![Taking_on_COVID-19_152x114_Image-01](https://user-images.githubusercontent.com/60756584/81207448-64ed1180-8f82-11ea-9a82-9daa46f411a6.jpg)

**Comment by Herm71** [comment]
Done.
