### ISSUE TITLE
Impact of Giving - Creating Opportunities tile

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#36]
Hi @Herm71,

Lets replace the image for the "Creating Opportunities" tile on the Impact of Giving page - Here is the new image.
![Cat-Ramirez (first_gen)](https://user-images.githubusercontent.com/60756584/81212153-4d655700-8f89-11ea-8530-f666902add46.jpg)
<img width="495" alt="Screen Shot 2020-05-06 at 10 16 21 AM" src="https://user-images.githubusercontent.com/60756584/81212160-51917480-8f89-11ea-9426-01f361be1bcb.png">

**Comment by Herm71** [comment]
This space is reserved for "Featured Stories" and is not "swappable" like the others. We need to find another story with a better fitting picture to include here.

**Comment by jhillard-ucsc** [comment]
You can switch this photo into the story that is linked. But please caption it with who she is.
