### ISSUE TITLE
Impact of Giving page banners

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#45]
Hi @Herm71,

I just had a quick tb with JD and we noticed that all pages after the first page carry over the banner image and the two tiles, but we don't think they need to carry over. Maybe you and Rob can discuss it, but it confused me. I almost thought it was a second and third version of the first page

**Comment by Herm71** [comment]
Look into pagination and if statement to see if you're not on the subsequent pages.

**Comment by knice** [comment]
https://jekyllrb.com/docs/pagination/
