### ISSUE TITLE
Photo adjustments - Home page

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#5]
The two feature photos on the home page need a little adjustment. Can we shift both of them to the left so more of the people on the right side of the images aren't so weirdly cropped? 
![Screen Shot 2020-03-06 at 9 37 13 AM](https://user-images.githubusercontent.com/60756584/76107981-951e3100-5f8e-11ea-9c13-b810447e31e1.png)

**Comment by Herm71** [comment]
As we discussed, Miranda is going to art-direct some different images with left-side offsets so faces aren't cut off.

**Comment by Herm71** [comment]
I think we got this one fixed. @Mirandapow uploaded fresh images.
