### ISSUE TITLE
Blue boxes

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#6]
It looks like all of the blue boxes have borders around them. Is this just a staging preview issue? If not, can they be removed?
![Screen Shot 2020-03-06 at 9 43 21 AM](https://user-images.githubusercontent.com/60756584/76108167-f2b27d80-5f8e-11ea-9748-ada50dcb182b.png)

**Comment by Herm71** [comment]
Removed the insets.
![Screenshot from 2020-03-06 14-30-06](https://user-images.githubusercontent.com/1000543/76127743-4fc22980-5fb7-11ea-847d-8d5869640de2.png)

**Comment by Herm71** [comment]
Closing.
