### ISSUE TITLE
Contact Page - new design

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#65]
On the "Contact" page, can we move the phone number and email back into the banner image and make them larger? Right now that they are below, too small, and seem to get lost.

@Herm71 - do you want me to provide a new visual design for this?

**Comment by knice** [comment]
- [ ] Can we remove the banner?
- [ ] Add more language around the phone and email
- [ ] Replace images for JD and Nathan
- [ ] Add Mark Davis and remove Jeff

Overall, we need to make it more obvious why and how someone would contact us.

**Comment by Herm71** [comment]
`We have a dedicated team ready to help you realize your philanthropic vision.' 

New phone number: `(831) 459-2501`

**Comment by knice** [comment]
## Contact page

- [ ] Align content left under page title
- [ ] Add header above team photos
- [ ] Align team photos left
- [ ] Make phone and email more prominent

**Comment by Herm71** [comment]
I believe this is as done as possible for right now. I am going to close this issue. Anything else that arises for this page can be discussed in a new issue.
