### ISSUE TITLE
Impact of Giving page header edit

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#66]
On the "Impact of Giving" page, I am still seeing the "-2", "-3", "-4" on the header after page one. Any way to remove that?

**Comment by Herm71** [comment]
@Mirandapow @knice That is intentional. It's to let the reader know what page of the archive they're on. I'm open to discussion, but I think for SEO and usability they should reamain.

**Comment by knice** [comment]
The Impact of Giving area doesn't paginate anymore. This issue doesn't exist.
