### ISSUE TITLE
Areas to Support - blue boxes

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#8]
It appears the blue boxes are not consistent in size. I do think we need to keep them all the same size to provide a clean look. We need to cut copy in the biggest box to get this to work.

The boxes should all be the same size across the whole site, if we can.

![Screen Shot 2020-03-06 at 9 49 53 AM](https://user-images.githubusercontent.com/60756584/76108825-2a6df500-5f90-11ea-8c45-41543dbcf452.png)

**Comment by Herm71** [comment]
That's correct. The boxes expand based on the text, so a little copy editing is needed.

**Comment by Herm71** [comment]
Use Flexbox or grid solution to enforce static heights.

**Comment by knice** [comment]
Short-term fix: remove the second sentence in the left card.

Then move this one to post-launch milestone.
