### ISSUE TITLE
Two Impact items for Rob

### ISSUE THREAD

**Issue by jhillard-ucsc** [ucsc/site-giving#89]
- [x] 1. How to links to the impact page in its "News" and "Donor Profiles" states.  (Or we can just take those links out.) 
- [x]  2. Making Link posts work: see the top three student stories, which load pages containing headlines only.

**Comment by knice** [comment]
I updated the Impact of Giving page to show the latest 10 stories from each of the three main categories (the video category is also working, but only linked in the footer). The category pages have all of the stories list in reverse chronology, and they are paginated.
