### ISSUE TITLE
Ways to Give - spacing

### ISSUE THREAD

**Issue by Mirandapow** [ucsc/site-giving#9]
Let's add more air between the feature image and the 5 ways to give. Maybe make it the same as the space you have between
![Screen Shot 2020-03-06 at 9 56 50 AM](https://user-images.githubusercontent.com/60756584/76109194-d3b4eb00-5f90-11ea-9001-b03a4c314196.png)
 the 5 ways to give and the start of the blue boxes?

**Comment by Herm71** [comment]
Added a 30px buffer.
![Screenshot from 2020-03-06 14-30-06](https://user-images.githubusercontent.com/1000543/76130711-a849f480-5fc0-11ea-884a-d740fd55edb8.png)
