### ISSUE TITLE
Wonky formatting two issues

### ISSUE THREAD

**Issue by jhillard-ucsc** [ucsc/site-giving#90]
On https://ucsc-giving.netlify.app/areas-to-support/academic-divisions-library/

- [x] Learn More buttons have weird hover style (Learn More is invisible until hover) These buttons also appear and do the same thing on the Colleges page.
- [ ] For list items, text is scrunched left

**Comment by Herm71** [comment]
I split this out into two issues. The "Learn more" button issue is now here: Issue #91
