### ISSUE TITLE
Add robots.txt to /reports/

### ISSUE THREAD

**Issue by Herm71** [ucsc/site-giving#99]
So Google doesn't crawl

**Comment by knice** [comment]
@Herm71 Be sure to add robots.txt to the root folder and [use the correct syntax to add no crawl directives](https://en.ryte.com/free-tools/robots-txt-generator/#allowing) for the reports folder. That way we have a global robots.txt file for other uses if need be.

**Comment by Herm71** [comment]
Added `robots.txt` to root, added `Disallow:` rule for `/reports/` tested on branch deploy using `https://en.ryte.com/free-tools/robots-txt/`. Worked. Issue closed.
